on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Clone or pull the repository
            if [ -d "/var/www/project" ]; then
              cd /var/www/project
              git pull origin staging
            else
              git clone https://github.com/kyawyenaingdev/example-app /var/www/project
              cd /var/www/project
              git checkout staging
              git pull origin staging
            fi

            # Rest of the deployment steps...
            # Install dependencies
            composer install --no-interaction --no-dev --prefer-dist

            # Copy and configure the .env file
            cp .env.example .env
            sed
