on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          ssh_options: "-o ForwardAgent=yes"
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          script: |
            # Clone or pull the repository
            if [ -d "/var/www/project" ]; then
              cd /var/www/project
              git pull origin staging
            else
              git clone git@github.com:kyawyenaingdev/example-app.git /var/www/project
              cd /var/www/project
              git checkout staging
              git pull origin staging
            fi

            # Rest of the deployment steps...
            # Install dependencies
            composer install --no-interaction --no-dev --prefer-dist

            # Copy and configure the .env file
            cp .env.staging .env
            sed -i "s/APP_ENV=.*/APP_ENV=production/" .env
            sed -i "s/APP_DEBUG=.*/APP_DEBUG=false/" .env

            # Generate application key
            php artisan key:generate

            # Run migrations and seeders
            php artisan migrate --force
            php artisan db:seed --force

            # Clear cache and optimize
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Restart necessary services (example: Apache, Nginx, etc.)
            sudo service apache2 restart
