name: Deploy

# Trigger the workflow on push and
# pull request events on the production branch
on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo Branch
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Set Environment Variable
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}"
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/exampleapp_github-actions
            sudo chown -R $USER:www-data /var/www/example-app
            sudo find /var/www/example-app -type f -exec chmod 644 {} \;  
            sudo find /var/www/example-app -type d -exec chmod 755 {} \;
            cd /var/www/example-app/
            sudo chmod +x .scripts/deploy.sh
            sudo chgrp -R www-data storage bootstrap/cache
            sudo chmod -R ug+rwx storage bootstrap/cache
            .scripts/deploy.sh "$BRANCH_NAME"